product_search/urls.py
from django.urls import path
from product_search.views import search

app_name = 'product'

urlpatterns = [
    path('', search, name="search"),
]

search_aggregator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  
    path('', include(('product_search.urls', 'product_search'), namespace='product')),
    path('admin/', admin.site.urls),
]

product_search/models.py
from django.db import models


# Create your models here.

# Fields - Product Name, URL, Image and Price 

class Product(models.Model):
    name = models.CharField(max_length=200, blank=False, unique=True)
    image = models.URLField(blank=False)
    url = models.TextField(blank=True)
    price = models.IntegerField(blank=False)

    def __str__(self):
        return self.name

product_search/views.py
from django.shortcuts import render
import requests
from product_search.models import Product
from django.views.decorators.csrf import csrf_exempt
import threading
import time
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

start = time.time()


def paytmMall(search_text):
    """
        Api to fetch data form Paytm Mall Provider
    :param search_text:
    :return: json object
    """
    extract_key = "grid_layout"  # as per resulted json "grid_layout" key has all products as values
    query = "https://search.paytm.com/v2/search?userQuery=" + search_text
    print(query, extract_key)
    try:
        response = requests.get(query)
        data = response.json()
        result = data[extract_key]  # as per resulted json "products" key has all products as values
        product_list = []

        for product in result:
            # Create product list
            product_list.append(Product(name=product['name'], price=product['offer_price'],
                                        url=product['url'], image=product['image_url']))

        # Call bulk_create to create records in a single call
        Product.objects.bulk_create(product_list)

        return data
    except json.decoder.JSONDecodeError as err:
        error, = err.args
        print("error for PAYTMALL ", error)
    except Exception as error:
        er, = error.args
        print(er)
        return er


def shopClues(search_text):
    """
        Api to fetch data form Shop Clues Provider
    :param search_text:
    :return: json object
    """
    extract_key = "products"
    query = "https://api.shopclues.com/api/v11/search?q=" + search_text + "&z=1&key=d12121c70dda5edfgd1df6633fdb36c0"
    print("FOR SHOP CLUE", query)
    try:
        response = requests.get(query)
        data = response.json()
        result = data[extract_key]  # as per resulted json "products" key has all products as values
        product_list = []

        for product in result:
            # Create product list
            product_list.append(Product(name=product['product'], price=product['price'],
                                        url=product['product_url'], image=product['image_url']))

        # Call bulk_create to create records in a single call
        Product.objects.bulk_create(product_list)

        print("ShopClues", product_list)
        return data
    except json.decoder.JSONDecodeError as err:
        error, = err.args
        print("error for ShopClues", error)
    except Exception as error:
        er, = error.args
        print(er)
        return er

    # Product.objects.filter(pk=some_value).update(field1='some value')


def tataCliq(search_text):
    """
        Api to fetch data form Tata Cliq Provider
    :param search_text:
    :return: json object
    """

    extract_key = "searchresult"  # as per resulted json "searchresult" key has all products as values
    query = "https://www.tatacliq.com/marketplacewebservices/v2/mpl/products/serpsearch?type=category&channel=mobile&pageSize=20&typeID=al&page=0&searchText=" + search_text + "&isFilter=false&isTextSearch=true"

    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, '
                                 'like Gecko) Chrome/50.0.2661.102 Safari/537.36',
                   "Content-Type": "application/x-www-form-urlencoded"}
        response = requests.get(query, headers=headers)

        data = response.json()
        result = data[extract_key]  # as per resulted json "products" key has all products as values
        product_list = []

        for product in result:
            # Create product list
            print(product)
            product_list.append(Product(name=product["productname"], price=product['sellingPrice']['value'],
                                        url=product['imageURL'], image=product['imageURL']))
            # since the tataCliq json doesn't have any product url

        # Call bulk_create to create records in a single call
        Product.objects.bulk_create(product_list)
        print("TataCliq", result)

    except json.decoder.JSONDecodeError as err:
        error, = err.args
        print("error for TataCliq", error)

    except Exception as error:
        er, = error.args
        print(er)
        return er


@csrf_exempt
def search(request):
    if request.POST:
        search_text = request.POST['search']

        lst = search_text.split(' ')
        if len(lst) > 1:
            search_text = '+'.join(lst)
        products = []
        print("Text to be searched", search_text)
        if Product.objects.filter(name__icontains=search_text).exists():
            product_list = Product.objects.filter(name__icontains=search_text).order_by('id')
            page = request.GET.get('page', 1)
            paginator = Paginator(product_list, 50)
            try:
                products = paginator.page(page)
            except PageNotAnInteger:
                products = paginator.page(1)
            except EmptyPage:
                products = paginator.page(paginator.num_pages)

                # creating threads
        t1 = threading.Thread(target=paytmMall, args=(search_text,), name='t1')
        t2 = threading.Thread(target=shopClues, args=(search_text,), name='t2')
        t3 = threading.Thread(target=tataCliq, args=(search_text,), name='t3')

        # starting threads
        t1.start()
        t2.start()
        t3.start()

        # wait until all threads finish
        t1.join()
        t2.join()
        t3.join()

        print("Elapsed Time: %s" % (time.time() - start))
        return render(request, 'search.html', {'error': '', 'data': products})

    else:
        return render(request, 'search.html', {'error': 'Please enter something', 'data': ''})

templates/search.html
<!DOCTYPE html>
{% load static %}
    <html>
    <head>
        <title>Search Aggregator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
    <div>

    <form class="example" style="margin:auto;max-width:500px" action="{% url 'product:search' %}" method="post">{% csrf_token %}

      <input type="text" placeholder="Search Products.." name="search" >
      <button type="submit"><i class="fa fa-search"></i></button>
    </form><hr>
        {% if data %}
         <div class="grid-container">
  {% for product in data %}
    <div class="row">
  <div class="column" style="background-color:white;">
          <img src={{ product.image }} alt="Avatar" style="width:200px;height:200px">
      <div>
          <span><b>{{ product.name }}</b></span>
          <br>
                        <span>INR {{ product.price }}</span>
          <br>
                  <span><a href={{ product.url }} target="_blank"> Buy Now</a> </span>
      </div>

  </div>
    </div>

         {% endfor %}
             </div>
  {% endif %}


{% if products.has_other_pages %}
  <ul class="pagination">
    {% if products.has_previous %}
      <li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in products.paginator.page_range %}
      {% if products.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if products.has_next %}
      <li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>

    </body>
    </html> 